apiVersion: v1
kind: Service
metadata:
  name: registration-app-service
  namespace: registration-app-aws
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}

  ports:
  - port: 80
    targetPort: {{ .Values.app.port }}
    nodePort: 32000

  type: NodePort
